title: "AutoWelt"
description: "Simple car listings with Jekyll + Decap CMS"

default_car_image: /assets/img/car-placeholder.jpeg

collections:
  cars:
    output: true # each car gets its own page under /cars/...
    permalink: /cars/:name/

defaults:
  - scope:
      path: ""
      type: cars
    values:
      layout: car

plugins:
  - jekyll-sitemap # /sitemap.xml for search engines


# Optional: set a baseurl if this is a project site (not username.github.io)
# baseurl: "/carsales-jekyll-website"