backend:
  name: github
  repo: OlehLazurkevych/olehlazurkevych.github.io
  branch: main
  base_url: https://netlifyfunctionsoauthforgithub.netlify.app
  auth_endpoint: /.netlify/functions/oauth-start
  site_domain: olehlazurkevych.github.io # optional but recommended

site_url: https://olehlazurkevych.github.io
display_url: olehlazurkevych.github.io

logo:
  src: /assets/img/logo.png
  show_in_header: true

media_folder: "assets/uploads/cars"   # where images are stored in repo
public_folder: "/assets/uploads/cars" # how the site references them

collections:
  - name: "cars"
    label: "Cars"
    folder: "_cars"
    create: true
    slug: "{{slug}}-{{year}}{{month}}{{day}}{{hour}}{{minute}}{{second}}"
    extension: "md"
    format: "frontmatter"
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "car" }
      - { label: "–î–∞—Ç–∞ –ø—É–±–ª—ñ–∫–∞—Ü—ñ—ó", name: "created_at", widget: "datetime", default: "{{now}}" }
      - { label: "–ó–∞–≥–æ–ª–æ–≤–æ–∫", name: "title", widget: "string", hint: "–ù–∞–ø—Ä–∏–∫–ª–∞–¥: Land Rover Range Rover HSE" }
      - { label: "–í–∞—Ä—Ç—ñ—Å—Ç—å (USD)", name: "price_usd", widget: "number", required: false, hint: "–í–∞—Ä—Ç—ñ—Å—Ç—å –≤–∫–∞–∑–∞—Ç–∏ —è–∫ —Ü—ñ–ª–µ —á–∏—Å–ª–æ –±–µ–∑ —Å–∏–º–≤–æ–ª—ñ–≤" }
      - { label: "–†—ñ–∫", name: "release_year", widget: "number", required: false }
      - { label: "–†—ñ–∫/–ú—ñ—Å—è—Ü—å", name: "alt_release_year", widget: "string", required: false, hint: "–ê–ª—å—Ç–µ—Ä–Ω–∞—Ç–∏–≤–∞ –¥–æ –ø–æ–ª—è –†—ñ–∫. –†—ñ–∫ —Ç–∞–∫–æ–∂ –±–∞–∂–∞–Ω–æ –≤–∫–∞–∑–∞—Ç–∏." }
      - { label: "–î–≤–∏–≥—É–Ω", name: "engine", widget: "string", required: false }
      - label: "–ü—Ä–∏–≤—ñ–¥"
        name: "drive"
        widget: "select"
        required: false
        options:
          - { label: "–ü–æ–≤–Ω–∏–π –ø—Ä–∏–≤—ñ–¥", value: "–ü–æ–≤–Ω–∏–π –ø—Ä–∏–≤—ñ–¥" }
          - { label: "–ü–µ—Ä–µ–¥–Ω—ñ–π –ø—Ä–∏–≤—ñ–¥",  value: "–ü–µ—Ä–µ–¥–Ω—ñ–π –ø—Ä–∏–≤—ñ–¥" }
          - { label: "–ó–∞–¥–Ω—ñ–π –ø—Ä–∏–≤—ñ–¥",  value: "–ó–∞–¥–Ω—ñ–π –ø—Ä–∏–≤—ñ–¥" }
      - { label: "–ü—ñ–¥ –∑–∞–≤–¥–∞—Ç–∫–æ–º", name: "under_deposit", widget: "boolean", default: false, required: false }
      - { label: "–ù–∞ –ø–ª–æ—â–∞–¥—Ü—ñ", name: "on_site", widget: "boolean", default: true }
      - label: "–§–æ—Ç–æ–≥—Ä–∞—Ñ—ñ—ó"
        name: "photos"
        widget: "list"
        required: false
        field:
          label: "–§–æ—Ç–æ"
          name: "photo"
          widget: "image"
          media_folder: "/assets/uploads/cars"
          public_folder: "/assets/uploads/cars"
      - { label: "–û–ø–∏—Å", name: "body", widget: "markdown", required: false }
      - { label: "–í—ñ–¥–µ–æ –ø–æ—Å–∏–ª–∞–Ω–Ω—è", name: "video_url", widget: "string", equired: false, hint: "https://www.instagram.com..." }
    sortable_fields: ["created_at", "title", "price_usd", "release_year"]
    view_groups:
      - label: "–ù–∞ –ø–ª–æ—â–∞–¥—Ü—ñ"
        field: "on_site"
        values:
          - { label: "–ê–≤—Ç–æ –Ω–∞ –ø–ª–æ—â–∞–¥—Ü—ñ", value: true }
          - { label: "–ê–≤—Ç–æ –≤ –¥–æ—Ä–æ–∑—ñ", value: false }
    view_filters:
      - label: "–ü—ñ–¥ –∑–∞–≤–¥–∞—Ç–∫–æ–º"
        field: "under_deposit"
        pattern: true
      - label: "–ù–µ –ø—ñ–¥ –∑–∞–≤–¥–∞—Ç–∫–æ–º"
        field: "under_deposit"
        pattern: false
      - label: "–ù–∞ –ø–ª–æ—â–∞–¥—Ü—ñ"
        field: "on_site"
        pattern: true
      - label: "–í –¥–æ—Ä–æ–∑—ñ"
        field: "on_site"
        pattern: false
    summary: "{{on_site | ternary('', 'üö¢')}}{{under_deposit | ternary('üí∏', '')}} ‚Ä¢ {{created_at | date('YYYY-MM-DD')}} ‚Ä¢ {{title}} {{release_year}} ${{price_usd | default('_')}}"
